#ifndef WARLOCK_SIMULATOR_TBC_ENUMS
#define WARLOCK_SIMULATOR_TBC_ENUMS

enum SpellSchool { NO_SCHOOL, SHADOW, FIRE };
enum SpellType { NO_SPELL_TYPE, AFFLICTION, DESTRUCTION };
enum PetName { NO_NAME, IMP, VOIDWALKER, SUCCUBUS, FELHUNTER, FELGUARD };
enum PetType { NO_PET_TYPE, MELEE, RANGED };
enum PetMode { NO_MODE, PASSIVE, AGGRESSIVE };
enum AttackType { NO_ATTACK_TYPE, PHYSICAL, MAGICAL };
enum SimulationType { NORMAL, ALL_ITEMS, STAT_WEIGHTS };

#endif