name: TypeScript Lint

on:
  push:
    branches:
      - master
    paths:
      - "public/**"
      - "src/**"
      - ".prettierrc"

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettier Action
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: "--write **/*.{js,jsx,ts,tsx} --config .prettierrc"
          commit_message: "Prettier Fixes"
          github_token: ${{ secrets.GITHUB_TOKEN }}
